language: go

os:
  - linux

go:
  - '1.11'

env:
  global:
    - GIT_NAME: Pei-Ming Wu
    - GIT_USER: mkfsn
    - GIT_REPO: blog
    - GIT_EMAIL: p408865@gmail.com
    - GITHUB_REPO: "${GIT_USER}/${GIT_REPO}"
    - secure: GscXN20tOPipggeYpIHe7aE/lW/adWDFk2D+o2uChBqpos8WESUNjKQQzQOVSlEAbAdu1+31PV7xhAog/5IXgYJj6KG0qrbtB0k3sAaxUJ8fJFXjZ84nA+PYZz2DhwRYByrVh/wWyzU34VPirBbGfKyCTU/1rXolaBgXUoSYA5iYfgqY0e0b9f0rTIqWIaJA5p36y+vlCGNN14ZICJNTKZJnwAat0GR1dAMxIlcgZlP39e2p4n+Gc11XxtPpSN1B6PGiTMNUc/Rki3bn+f5Wg7x/crJMDCQC53LMnKxC4+VpzwkJfQv/1e8NGpzqTgdLkybeirkYdHOadBnvCyHN6n9+KZ0NF2aOZ7JOUH9hAd1eEAKePl9jCObzbR9sSr3I/+/uSe1YsLtYXawbgAn3iNvtRDdJbKCQFeXblSxzJd7ssk8WXgtUglVQGeaFOHHHAtVNdjVsuJQtCJ4B7Ny+U12GIEj9bbve4QkVyLp9YrJgv9JZPrbgEglerh23AJXF/7RMiEyJZK2vi+XGFLvBm4R5lMSW/aX8v7W9DAJ5wfNd0MqFg2T5BjSEGkKUdxqra860cmlXed/w42KTiG9+brwnSdI7xF71GOhVFvqOYJ1Fu8LczG7YJwMjvCTliT/8ry610brBE4nRhgJuWGB1pgEcv1I1CFGTgtdC8Q72XnM=

before_install:
  # git config
  - git config --global user.email ${GIT_EMAIL}
  - git config --global user.name ${GIT_NAME}
  - git config --global push.default simple
  # go dependencies
  - GO111MODULE=on go get github.com/gohugoio/hugo

before_script:
  # git
  - git clone "https://github.com/${GITHUB_REPO}.git" --branch gh-pages public

script: hugo

after_success:
  - cd public
  - git add --all
  - git commit -m "Publishing to gh-pages from Travis `date`"
  - cd ..
  - git push --force --quiet "https://${GIT_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git" origin gh-pages

branches:
  only:
    - hugo
    - travis
