language: go

os:
  - linux

go:
  - '1.11'

env:
  global:
    - GITHUB_REPO: "$GIT_USER/$GIT_REPO"
    - secure: "coOQfIhp1m0IZ9OoL2pQQ/sy5xM3z9r4Dx2AsK9Metslw8jxSHSw3LwQ0bckSUjOcDnjU6I9gRtLaFGHhgN/MIBiBuZa01YKspEdDj0LVHkXhY79msp5jvIwNrLg6uu3gDluW4irlSx0CMrVemUgbBb9JrAD2wl4tvqa9haQGdqrKYN/qgCO64Ms7sPIEUrF1XZ5SK1Yeo4LVYlGq7GUhwo+yaZbwmX7O+e+Z3WkFRaixm1o10Fz6rcVklJz/DfGR0zzKepYPXGtkwLzQJDM0yibZpuqSXmzvwpga4ED4XRnfklOJeTbHhAZivHoZlqfohGpjD41Gnw4V1aV/O0It+Ns6S2gvron5A3RdaBR0M9Ydj54IVHy0+jCmEdAl6nqHr90+VMo6gSRI3r0wlo+sNIXYMxyZCjWB97wAnBZQJnCW+1+d/8/3oZQJu9DguNrjCM+1N0R5/NG3N5Zfb7TfiPbc6F+MQqHZ/C08hDvnQXzcMhJpeepYu2Rohm6XXCv1lakeiZyq28a9zvjuNa/nEKzgIKwhFxCh3rNuI3z4LI6G6awP2XvglcsAdkANRS97DoJBy8wf1w6hVOgPN20xoIOOPqFe4yVZiXFmINT7F0tgDIjYG1OKJI6HCgHua1GKCquPY1VQ6dxBhrANEtz1Ff4OQnWyuvBTElBaticlHA="

before_install:
  # git config
  - git config --global user.email ${GIT_EMAIL}
  - git config --global user.name ${GIT_NAME}
  - git config --global push.default simple
  # go dependencies
  - GO111MODULE=on go get github.com/gohugoio/hugo

before_script:
  # git
  - git clone "https://github.com/${GITHUB_REPO}.git" --branch gh-pages public

script: hugo

after_success:
  - cd public
  - git add --all
  - git commit -m "Publishing to gh-pages from Travis `date`"
  - cd ..
  - git push --force --quiet "https://${GIT_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git" origin gh-pages

branches:
  only:
    - hugo
    - travis
