language: go

os:
  - linux

go:
  - '1.11'

env:
  global:
    secure: 'Y2CW43227jL/+r10CyFt93hSM4irXj8YfL8v/rASr9g37c5YdQyrcGR4kozuBC1mDAsqVJ4e7I1nZxcYELzFpXq405S4eG1tD9qdbAQcdnfaj8JunN6wPbOLWLflVvHCmhDZ2mbj208D5MkAHm24cFdf/HOp7F822iUSGRhGs3bO15H5KrIpQi+C0nvaLcX+eh830Hfb1vlOSMKS+aKM//DOUsxYKoHyuOEyvkKJxa4Qi1HFEkLMKrUxQK3qF4CQfq1YkJ+eIx4BkHi7KTSmNq3hq24uo4r/iqa1kNXzmvOGIN/u8TruUmAHBn0GuxKqy7H9ZeGHbyRmF8NJRKBv3ytFhBJfe8UU40tSPndoM6QmZgx/ihqs50a5Hi/n8JEzMdTrhD6g4EJfyaqG8rYXMGsQLd5g/cyG2lSD1cd1WmalxDuG3xbvmcTYWGxpWPigt9maZ709BU2TKon24TOT31bsfCZ5tEdtT1qvqoriW9aLxR7ccSV+AnY77vU63EkWAaEApudsv6751dEZo5ms2oNSfQ5DTXZndbSuyfZn6wOX0A8pBq9sqytr/oPEmw+lSKI6Q57LaWo9TjYtofRYQDA4nfWQ0W5D/3BewyOXeghYgdzrE8vl81iHRJYuWkKMnW+hCPAEW+5pzOgjd+Qfbo468B2J2i96VWFgUJH29A0='
    GITHUB_REPO: "$GIT_USER/$GIT_REPO"

before_install:
  # git config
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"
  - git config --global push.default simple
  # go dependencies
  - GO111MODULE=on go get github.com/gohugoio/hugo

before_script:
  # git
  - echo $GITHUB_REPO
  - echo $GIT_NAME
  - echo $GIT_USER
  - echo $GIT_REPO
  - git clone "https://github.com/$GITHUB_REPO.git" --branch gh-pages public

script: hugo

after_success:
  - cd public
  - git add --all
  - git commit -m "Publishing to gh-pages from Travis `date`"
  - cd ..
  - git push --force --quiet "https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git" origin gh-pages

branches:
  only:
    - hugo
    - travis
